export { default as BootScene } from './boot'
export { default as GameScene } from './game'
export { default as MainMenuScene } from './mainMenu'
export { default as SplashScene } from './splash'
export { default as HuDScene } from './hud'
